T: 750
batch_size: 64
bits_per_feature: 25
buffer_size: 2000
device: CPU
epochs: 2
exploration_prob_decay: 0.001
exploration_prob_init: 1.0
gamma: 0.75
nr_of_clauses: 1000
nr_of_episodes: 4951
nr_of_steps: 131873
s: 10
save: true
test_freq: 50
threshold_score: 450
weighted_clauses: true
y_max: 100
y_min: 0
